/**
 * Topics a work theme must never touch: health, money, family, legal trouble and secrets. Generic
 * words only; a theme containing one (or a short ending on it: "loans", "doctors") is dropped, and
 * counted, never shown.
 */
export const PRIVACY_WORDS = [
  "doctor",
  "dentist",
  "hospital",
  "diagnosis",
  "medication",
  "medical",
  "prescription",
  "therapy",
  "therapist",
  "counselling",
  "counseling",
  "surgery",
  "pregnant",
  "pregnancy",
  "illness",
  "cancer",
  "depression",
  "anxiety",
  "salary",
  "payslip",
  "loan",
  "mortgage",
  "debt",
  "tax",
  "bankrupt",
  "invoice",
  "credit card",
  "divorce",
  "wedding",
  "funeral",
  "girlfriend",
  "boyfriend",
  "wife",
  "husband",
  "baby",
  "lawsuit",
  "lawyer",
  "court",
  "visa",
  "passport",
  "arrest",
  "police",
  "password",
  "passcode",
  "secret",
  "login",
  "token",
  "credential",
  "api key",
  "apikey",
] as const;
