/**
 * Private-context cues (spec §18): wording that marks a whole screen as somewhere private. A
 * frame whose text holds any of them is dropped before an excerpt is cut. The list is deliberately
 * wide: over-excluding is the intended failure, because a hit has no app name to check.
 *
 * Matched as whole words (a trailing "s" or "es" is allowed) on canonical text, with other
 * characters allowed between the letters of a cue of four or more letters and one between those of
 * a shorter cue ("t a x"), and also on a copy with scanner mistakes folded (see frame-checks.ts). A cue therefore does not
 * fire inside another word ("tax" is not "syntax"), so list each form that should match.
 */
export const PRIVATE_CUES = [
  // Password managers, sign-in and one-time codes.
  "1password",
  "bitwarden",
  "lastpass",
  "dashlane",
  "keepass",
  "keychain",
  "password",
  "passcode",
  "passphrase",
  "passkey",
  "master password",
  "password manager",
  "sign in",
  "signed in",
  "sign out",
  "log in",
  "logged in",
  "login",
  "logon",
  "one-time code",
  "one-time password",
  "verification code",
  "security code",
  "recovery code",
  "backup code",
  "authenticator",
  "two-factor",
  "2fa",
  // Email.
  "inbox",
  "unread",
  "compose",
  "gmail",
  "webmail",
  "outlook",
  "thunderbird",
  "protonmail",
  "proton mail",
  "mailbox",
  "mail",
  "reply all",
  "sent items",
  "new message",
  // Chat, messaging and calls.
  "slack",
  "discord",
  "whatsapp",
  "telegram",
  "messenger",
  "imessage",
  "direct message",
  "microsoft teams",
  "google chat",
  "zoom meeting",
  "google meet",
  "webex",
  "facetime",
  "video call",
  "join meeting",
  // Calendar.
  "calendar",
  "rsvp",
  "meeting invite",
  // Banking, payments, payroll and billing.
  "bank",
  "banking",
  "bsb",
  "iban",
  "sort code",
  "routing number",
  "account number",
  "account balance",
  "available balance",
  "card number",
  "cvv",
  "cvc",
  "credit card",
  "debit card",
  "bpay",
  "paypal",
  "venmo",
  "revolut",
  "transferwise",
  "transaction history",
  "invoice",
  "payroll",
  "payslip",
  "salary",
  "superannuation",
  "receipt",
  // Tax and government portals.
  "tax",
  "tax return",
  "tax file number",
  "tax office",
  "irs",
  "hmrc",
  "mygov",
  "centrelink",
  "social security",
  "national insurance",
  "passport",
  "driver licence",
  "driver license",
  // Health portals.
  "patient",
  "patient portal",
  "medicare",
  "prescription",
  "diagnosis",
  "test results",
  "lab results",
  "pathology",
  "telehealth",
  "pharmacy",
  "hospital",
  "clinic",
  "medication",
  // Private windows.
  "private browsing",
  "private window",
  "incognito",
  "inprivate",
  // Plain words that mark everyday private use, and short forms.
  "email",
  "messages",
  "chat",
  "dm",
  "signal",
  "payment",
  "checkout",
  "billing",
  "statement",
  "balance",
  "otp",
  "username",
  "credential",
  "pin",
  "ssn",
  "wallet",
  "seed phrase",
  "date of birth",
  "dob",
  "medical",
  "doctor",
  "signing in",
  "logging in",
  "signing up",
  // Other languages (accents are stripped before matching).
  "passwort",
  "posteingang",
  "anmelden",
  "kennwort",
  "contraseña",
  "correo",
  "bandeja de entrada",
  "iniciar sesion",
  "mot de passe",
  "connexion",
  "boite de reception",
  "banque",
  "banco",
  "senha",
  "konto",
  "kontostand",
  "bankkonto",
] as const;
